# Generated by Django 4.2.23 on 2026-04-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_fee_module_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='scholarship_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
