# Generated by Django 4.2.23 on 2026-04-23 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_section', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='period',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.section'),
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='gradesubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.school'),
        ),
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='book',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='schools.school'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('section', 'day', 'period_number')},
        ),
        migrations.AlterUniqueTogether(
            name='gradesubject',
            unique_together={('grade', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('school', 'name')},
        ),
    ]
